# (recursive) One horizontal slice of the vegetation-sparing carve, at height
# .cy above the rail (positioned there by the recursion; carve starts it at
# the rail cell with .cy 0 and it climbs to .ch inclusive).
#
# Each cell is cleared UNLESS it holds natural vegetation (the
# #infinite_rail:keep block tag, generated by the build from the shared
# vegetation.js). The two side cells are always vegetation-sparing; the
# center cell only participates in veg mode (.veg 1) and only from 2 above
# the rail up (carve already cleared the envelope below, and carve_center
# owns the center of full-clear columns).
execute unless block ~ ~ ~-1 #infinite_rail:keep run setblock ~ ~ ~-1 minecraft:air
execute unless block ~ ~ ~1 #infinite_rail:keep run setblock ~ ~ ~1 minecraft:air
execute if score .veg ir matches 1 if score .cy ir matches 2.. unless block ~ ~ ~ #infinite_rail:keep run setblock ~ ~ ~ minecraft:air
scoreboard players add .cy ir 1
execute if score .cy ir <= .ch ir positioned ~ ~1 ~ run function infinite_rail:carve_layer
